### ISSUE TITLE
Unable to generate when API includes `/health` endpoint

### ISSUE THREAD

**Issue by jbrooksuk** [crescat-io/saloon-sdk-generator#1]
Given an [API spec file](https://developers.checkmango.com/operation/operation-getcurrentteam) that includes a `/health` endpoint, the package is unable to generate an SDK.

```
In PhpNamespace.php line 267:

  Name 'Health' used already as alias for Checkmango\Requests\Health\Health.

```

**Comment by HelgeSverre** [comment]
Fixed in [v1.0.1](https://github.com/crescat-io/saloon-sdk-generator/releases/tag/v1.0.1)
