### ISSUE TITLE
[Question] Is it possible to use this within a Laravel package?

### ISSUE THREAD

**Issue by SuperDJ** [crescat-io/saloon-sdk-generator#16]
As it say in the title, is it possible to use this within a Laravel package? When creating a Laravel package there is no artisan file. And when you add one it gives an error on this line https://github.com/crescat-io/saloon-sdk-generator/blob/64338f69c0ec2b0c02b4c664a8e93414c0d8ee8c/bootstrap/app.php#L14

**Comment by HelgeSverre** [comment]
You are meant to composer require it globally using 
```composer global require crescat-io/saloon-sdk-generator```

Or pull it into your project (in which case it is meant to be used programmatically ([see](https://github.com/crescat-io/saloon-sdk-generator?tab=readme-ov-file#using-the-code-generator-and-parser-programmatically)) to generate code, not be ran via `php artisan`
