### ISSUE TITLE
Reserved Word Protection

### ISSUE THREAD

**Issue by bobbyshaw** [crescat-io/saloon-sdk-generator#4]
Hi @HelgeSverre! Thanks for this project. I'm just trying it out and I ran into an error when a Request class is created with a reserved word. [Here](https://github.com/bigcommerce/api-specs/blob/main/reference/tax_provider.yml#L309), you will see an endpoint `/void` which then errors when trying to create a class `Void`.

Initially I replaced the `RequestGenerator` with a version that would catch [the exception that's thrown](https://github.com/nette/php-generator/blob/9d8f86a5c5683e881733cbd368908f560c9f7785/src/PhpGenerator/ClassLike.php#L91) and then try again with a suffix, e.g. `VoidRequest`.

However, that then has a problem where the same logic is required in the `ResourceGenerator`.

So then I was wondering if a check for reserved words might be better done somewhere centrally, like in the `NameHelper` [here](https://github.com/crescat-io/saloon-sdk-generator/blob/2f71b1c21e549b1a90979149b8f0b92d763f847c/src/Helpers/NameHelper.php#L65).

The challenge then is knowing how to adjust the class name with an appropriate suffix. 

If you have advice on a route you would prefer, I'd be happy to work on a PR when I have a moment.

**Comment by HelgeSverre** [comment]
Hey @bobbyshaw.

Whipped up a quick workaround for this on this branch: https://github.com/crescat-io/saloon-sdk-generator/compare/master...feature/name-collision-reserved-keywords 

Let me know if that works for you, its slightly crude, so there might be a better way to do this, but you can at least try it out now :)

**Comment by bobbyshaw** [comment]
Hi Helge, I've just tested this and it worked great for me! I'll delete my RequestGenerator override again 😀. 

Thanks

**Comment by HelgeSverre** [comment]
Yw, i see that in the Nette phpgenerator file you referenced there is a handy helper for checking if something is a valid name, didn't catch that the first time, will change the implementation to use that instead whenever i get around to it.

**Comment by HelgeSverre** [comment]
Merged into master

**Comment by bobbyshaw** [comment]
Thank you!
