### ISSUE TITLE
Soap API Generation (WSDL interpreter?)

### ISSUE THREAD

**Issue by Youssef-Azijni** [crescat-io/saloon-sdk-generator#7]
My colleagues and I enjoy how Saloon makes API integration easier, and gives us a common well documented way of interacting with them. However, we depend on some API's that use the SOAP protocol. Would it be possible to extend the SDK generator to create Saloon SDK's a la [Providr.io, and their WsdlToPhp](https://github.com/WsdlToPhp/PackageGenerator)

**Comment by HelgeSverre** [comment]
Supporting SOAP APIs is a little bit outside of what we aim to do with this package at this time, closing this for now.
